Implemented updated auth SDK
arcana-network/developer-dashboard pull request #45
Opened 2022-02-02 06:05 UTC by shrinathprabhu

1. Replaced static login types with SocialLoginType constants
2. Updated the auth with AuthProvider.init method
3. Moved userinfo fetching to SSORedirect page
4. Replaced popup flow with redirect flow

# Pull Request Template

Resolves or continues [AR-XXX](...).

## Blocking dependencies

- [AR-YYY](...)
- [AR-ZZZ](...)

## Changes

Please include a summary of the changes and any relavant context not convered in the issue ticket. You can assume that reviewers will begin by reading the description of the linked issue.

When making primarily visual changes, it's helpful to include before and after screenshots.

## Checklist

- [ ] The branch name follows the format: `developer/AR-XXX-issue-name`.
- [ ] The changes have been tested locally.

2022-03-29 14:17 UTC, ajithranka requested changes
Question: Why did we switch from the popup flow to the redirect flow?

2022-03-29 14:17 UTC, ajithranka commented on src/pages/AppLoginV2.vue
> +        console.log({ userInfo, privateKey });
Stray console.log.

2022-03-29 14:17 UTC, ajithranka commented on src/use/arcanaAuth.js
> +    console.log("After Init");
Stray console.log.

2022-03-29 15:21 UTC, shrinathprabhu commented on src/pages/AppLoginV2.vue
> +        console.log({ userInfo, privateKey });
Yeah

2022-03-30 05:01 UTC, shrinathprabhu commented
> Question: Why did we switch from the popup flow to the redirect flow? If we are allowing configuring the flow type in the environment variable, we should keep the SSORedirect component.

1. We required redirect flow to support mobile browsers and older version of Safari. In those popup mode doesn't work, so we implemented redirect mode in sdk. So if anyone wants to develop apps for mobile browsers, they can use redirect mode. We want our dashboard to be supported in mobile browsers as of now. We can discuss this with the team
2. Even if we change flow type from `.env`, it'll still require SSORedirect code to be changed, since in `popup` flow we use `AuthProvider.handleRedirect()` in SSORedirect and in `redirect` flow we directly use `authInstance.fetchUserInfo()`. Changing mode will still require code changes and won't be handled out of the box even if we keep `SSORedirect.vue`. For `redirect` flow we don't actually need SSORedirect as the entire thing will be handled in login page itself

2022-03-30 05:25 UTC, ajithranka commented
> > Question: Why did we switch from the popup flow to the redirect flow? If we are allowing configuring the flow type in the environment variable, we should keep the SSORedirect component.
> 
> 1. We required redirect flow to support mobile browsers and older version of Safari. In those popup mode doesn't work, so we implemented redirect mode in sdk. So if anyone wants to develop apps for mobile browsers, they can use redirect mode. We want our dashboard to be supported in mobile browsers as of now. We can discuss this with the team
> 2. Even if we change flow type from `.env`, it'll still require SSORedirect code to be changed, since in `popup` flow we use `AuthProvider.handleRedirect()` in SSORedirect and in `redirect` flow we directly use `authInstance.fetchUserInfo()`. Changing mode will still require code changes and won't be handled out of the box even if we keep `SSORedirect.vue`. For `redirect` flow we don't actually need SSORedirect as the entire thing will be handled in login page itself

Makes sense, @shrinathprabhu. Thanks for the explanation. 

Should we remove the `VITE_ARCANA_AUTH_FLOW` variable from `.env` and set it to "redirect" in the code?

2022-03-30 05:38 UTC, shrinathprabhu commented
> > > Question: Why did we switch from the popup flow to the redirect flow? If we are allowing configuring the flow type in the environment variable, we should keep the SSORedirect component.
> > 
> > 
> > 
> > 1. We required redirect flow to support mobile browsers and older version of Safari. In those popup mode doesn't work, so we implemented redirect mode in sdk. So if anyone wants to develop apps for mobile browsers, they can use redirect mode. We want our dashboard to be supported in mobile browsers as of now. We can discuss this with the team
> > 2. Even if we change flow type from `.env`, it'll still require SSORedirect code to be changed, since in `popup` flow we use `AuthProvider.handleRedirect()` in SSORedirect and in `redirect` flow we directly use `authInstance.fetchUserInfo()`. Changing mode will still require code changes and won't be handled out of the box even if we keep `SSORedirect.vue`. For `redirect` flow we don't actually need SSORedirect as the entire thing will be handled in login page itself
> 
> Makes sense, @shrinathprabhu. Thanks for the explanation.
> 
> Should we remove the `VITE_ARCANA_AUTH_FLOW` variable from `.env` and set it to "redirect" in the code?

Yeah we can

2022-03-30 05:55 UTC, ajithranka approved these changes
Looks good, thanks @shrinathprabhu.

2022-03-30 07:16 UTC, merged